language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

before_install:
  - if [[ $TRAVIS_BRANCH == greenkeeper* ]]; then npm install -g greenkeeper-lockfile; fi

install:
  - if [[ $TRAVIS_BRANCH == greenkeeper* ]]; then npm install; else npm ci; fi

before_script: if [[ $TRAVIS_BRANCH == greenkeeper* ]]; then greenkeeper-lockfile-update; fi
after_script: if [[ $TRAVIS_BRANCH == greenkeeper* ]]; then greenkeeper-lockfile-upload; fi

script:
  - 'if [ $HAPI_VERSION ]; then npm install hapi@^$HAPI_VERSION.0.0 || echo "done"; fi'
  - "if [ $LINT ]; then npm run lint; fi"
  - "if [ $COVERAGE ]; then npm run cover && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info; fi"
  - "if [ $RUN_TEST ]; then npm run test; fi"

jobs:
  include:
    - stage: tests
      node_js: 8
      env:
        - RUN_TEST=true

    - stage: tests
      node_js: 11
      env:
        - RUN_TEST=true

    - stage: tests
      node_js: 10
      env:
        - RUN_TEST=true

    - stage: tests
      node_js: node
      env:
        - RUN_TEST=true

    - stage: coverage
      node_js: 8
      env:
        - COVERAGE=true

    - stage: lint
      node_js: 8
      env: LINT=true
